User_Authentication/User_Auth/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from django.shortcuts import render

def about(request):
    return render(request,'about_me.html')

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('accounts/' , include('users.urls')),
    path('about_me/',about,name='about_me'),
    path('',about),
    
    # Password reset URLs
    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]  

User_Authentication/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    # UNLOGINED  PAGES 
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('home/',views.home, name='home'),
    
      #confirm account
    path('confirm/<uidb64>/<token>/', views.confirm_registration, name='confirm_registration'),
    path('succes',views.succes_registration, name='succes'),

    # LOGINED PAGES
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('404/', views.view_404, name='404'),
    path('users/', views.user_list_view, name='user_list'),
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
]

User_Authentication/users/models.py
from django.db import models

# Create your models here.

User_Authentication/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
      model = User
      fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
      email = self.cleaned_data.get('email')
      if User.objects.filter(email=email).exists():
          raise forms.ValidationError('Email is already registered.')
      return email

User_Authentication/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

# for email confirm
from django.contrib.auth.models import User
from django.utils.encoding import force_str
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.contrib import messages
from .signals import send_confirmation_email

# for users views 
from django.views.generic import DetailView


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save to the database yet
            user.is_active = False          # Mark user as inactive until email confirmation
            user.save()
            send_confirmation_email(sender=user.__class__, instance=user, created=True)
            messages.success(request, 'Registration successful! Please confirm your email to complete registration.')
            
            return redirect('users:login')  # Redirect to login after showing success message
    else:
        form = UserRegistrationForm()
    
    return render(request, 'registration/register.html', {'form': form})

@staff_member_required
def admin_view(request):
    return render(request, 'users/admin.html')

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def user_list_view(request):
    query = request.GET.get('q')  # Get the search query from the GET request
    if query:
        # Filter users based on username, first name, or email
        users = User.objects.filter( username__icontains=query)
        return render(request, 'users/user_list.html', {'users': users})
    else:
        users = User.objects.all().order_by("username")
        return render(request, 'users/user_list.html', {'users': users})

@login_required
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'users/user_detail.html', {'user': user})

def view_404(request):
    return render(request,'404.html')

def confirm_registration(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))          # Decode the base64-encoded user ID
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('users:succes')                         # Redirect to the login page or a success page
    else:
        return render(request, 'invalid_confirmation.html')     # Show an error page if the token is invalid

def succes_registration(request):
    return render(request, 'users/succes.html')

def home(request):
    return render(request, 'home.html')

User_Authentication/templates/about_me.html
{% extends "base.html" %}
{% block title %} Complete {% endblock %}

{% block content %}
<h1 style='color:red;' >About Me</h1>
<p>Hello there, my name is Federico Guakinchay.</p>
<p>I am a junior full-stack developer.</p>
<p>I have knowledge of HTML, CSS, JavaScript, and Python.</p>
<p>I am also learning Django and React.js.</p>
<br>
<p>This page is part of my effort to create a better portfolio.</p>
{% endblock %}

User_Authentication/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <!-- Navigation Bar  -->
    <nav>
        <ul>
            <li> <a href="{% url 'users:home' %}"> App </a> </li>
            <li class='none-navbar'>  </li>
            {% if user.is_authenticated %}
                {% if request.resolver_match.url_name != 'profile' %}
                    <li> <a href="{% url 'users:profile' %}">My_Profile</a> </li>
                {% endif %}
                <li class='logout-link'> <a href="{% url 'users:logout' %}" >Logout</a> </li>
                {% if request.user.is_superuser %}
                    <li> <a href="{% url 'admin:index' %}"> Django_Admin </a> </li>
                {% endif %}
                {% if request.user.is_staff %}
                    {% if request.resolver_match.url_name != 'admin_view' %}
                        <li> <a href="{% url 'users:admin_view' %}">Staff_Site</a> </li>
                    {% endif %}
                {% endif %}
                    {% if request.resolver_match.url_name != 'user_list' %}
                        <li> <a href="{% url 'users:user_list' %}"> Search_Users </a> </li>
                    {% endif %}
            {% else %}
                {% if request.resolver_match.url_name != 'login' %}
                    <li class='login-link'> <a href="{% url 'users:login' %}">Login</a> </li>
                {% endif %}
                {% if request.resolver_match.url_name != 'register' %}
                    <li class='register-link'> <a href="{% url 'users:register' %}">Register</a> </li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>

    <!-- Main Content -->
    <main>
        <div>
            {% block content %}
            <!-- Page-specific content will be rendered here -->
            {% endblock %}
        </div>
        {% if messages %}
            <ul>
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    </main>
    <!-- Footer -->
    <footer>
        <div>
            <span>&copy; 2024 My Django App. All rights reserved.</span>
            <span>&copy; Made  by Federico Guakinchay</span>
        </div>

        <a href={% url "about_me" %}> <span>about me </span> </a>
    </footer>
</body>
</html>

User_Authentication/users/templates/confirmation_email.html
<p>Hello,</p>
<p>You requested to create an account on my Django app.</p>
<p>Please confirm your registration by clicking the link below:</p>
<p><a href="{{ confirmation_link }}">Confirm Registration</a></p>
<br>
<p>If this wasn't you, you can ignore this email.</p>
<br>
<div>
  <span>&copy; 2024 My Django App. All rights reserved.</span>
  <span>&copy; Created by Federico Guakinchay</span>
</div>

User_Authentication/users/templates/home.html
{% extends "base.html" %}
{% block title %}home{% endblock title %}

{% block content %}
  <h1> my app title </h1>
  <h3>  this is a space to make a little explanation of  the app </h3>
{% endblock content %}

User_Authentication/users/templates/invalid_confirmation.html
{% extends "base.html" %}
{% block title %} Complete {% endblock %}

{% block content %}
  <h1>not valid confirmation</h1>
  <a href="{% url 'users:login' %}">
    <button>Return to login</button>
  </a>password.</p>
{% endblock %}

User_Authentication/users/templates/users/admin.html
{% extends "base.html" %}
{% block title %} staff site  {% endblock title %}

{% block content %}
<h1>only a staff and super users can see this page </h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem culpa eius libero, ea consequatur ab, incidunt sed debitis consectetur doloremque quibusdam numquam cum eveniet autem temporibus, modi placeat eaque sunt!</p>
{% endblock content %}

User_Authentication/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}

{% block content %}
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<br>
<a href="{% url 'password_reset' %}"> you forgot your password?</a><br>
<div class='card-content'>
    <h1> users to test </h1>
    <div class='card'>
        <p>username: Alan</p>
        <p>status  : super_user</p>
        <p>password: J8k@3Fp!zB4w</p>
    </div>
    <div class='card'>
        <p>username: Mark</p>
        <p>status  : staff_user</p>
        <p>password: Q7$YpL9xnV2</p>
    </div>
    <div class='card'>
        <p>username: Steve</p>
        <p>status  : normal_user</p>
        <p>password: A3s#D8eW!t7z</p>
    </div>
</div>
<style>
    .card-content{
        display: flex;
        margin: 20px;
        box-sizing: border-box;
        flex-wrap: wrap;
        width: fit-content;
        justify-content: center;
        gap: 10px;
        h1{
            width: 100%;
        }
        .card{
            text-align: left;
            background-color: #333;
            width: 220px;
            border-radius: 25px;
            padding: 10px;
            &:hover{background-color: #444;}
        }
    }
</style>
{% endblock content %}

User_Authentication/users/templates/users/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock title %}

{% block content %}
  <h1>you are login out </h1>
  <a href="{% url 'users:profile' %}">
    <button>Return to login</button>
  </a>
{% endblock content %}

User_Authentication/users/templates/users/profile.html
{% extends "base.html" %}
{% block title %}my profile{% endblock title %}

{% block content %}
<p>Welcome, {{ request.user.username }}!</p>
<p>this page have to contain my info </p>
{% if request.user.is_superuser %}
  <p>You have super user  permision !</p>
{% elif request.user.is_staff %}
  <p>You are a staff member!</p>
{% else %}
  <p>You are a user!</p>
{% endif %}
<p> your first name : {{request.user.first_name}}</p>
<p> your last name  : {{request.user.last_name}}</p>
<p> your email      : -----------</p>
{% endblock content %}

User_Authentication/users/templates/users/succes.html
{% extends "base.html" %}
{% block title %}register success {{user.username}}{% endblock title %}

{% block content %}
<h1> {{request.user.username}} Your account was registered successfully! </h1>
{% endblock content %}

User_Authentication/users/templates/users/user_detail.html
{% extends "base.html" %}
{% block title %}user : {{user.username}}{% endblock title %}

{% block content %}
<h1>this page have to contain the info of the user </h1>
<h2>user name :  {{user.username}}</h2>
{% if user.email %}
<p> email : {{ user.email }}</p>
{% else %}
<p> email :  null</p>
{% endif %}
<h3> user status </h3>
{% if user.is_superuser %}
<p>this user have <b style='color: #00f;'>super_user</b> permission</p>
{% elif user.is_staff %}
<p>this user have  <b style='color: #00f;'>staff</b> permission</p>
{% else %}
<p>this user dont have any permission</p>
{% endif %}
{% endblock content %}

User_Authentication/users/templates/users/user_list.html
{% extends "base.html" %}
{% block title %}users list{% endblock title %}

{% block content %}
<style> 
  @media only screen and (max-width: 750px) {
    .email-td-field{
      display: none;
    }
  }
</style>
<div class='employees-list'>
<h1> list of users </h1>
<form method="GET" action="{% url 'users:user_list' %}" style='margin-bottom: 25px;'>
  <input type="text" name="q" placeholder="Search users..." value="{{ request.GET.q }}">
  <button type="submit">Search</button>
</form>
<table>
  <tr>
    <td>name</td>
    <td>id</td>
    <td> user-type </td>
    <td class='email-td-field'>email</td>
    <td></td>
  </tr>
{% for user in users %}
{% if user != request.user%}
  <tr>
    <td> {{user.username}} </td>
    <td> {{user.id}} </td>
    {% if user.is_superuser %}
    <td> super </td>
    {% elif user.is_staff %}
    <td> staff </td>
    {% else %}
    <td> normal </td>
    {% endif %}
    {% if user.email %}
    <td class='email-td-field' > {{ user.email }} </td>
    {% else %}
    <td class='email-td-field'> ---- </td>
    {% endif %}
    <td><a href="{% url 'users:user_detail' user.id %}"> <button>view</button> </a></td>
  </tr>
  {% endif %}
  {% endfor %}
</table>
{%if not users %}
  <h1 style='margin: 12% auto;'> don't found users </h1>
{%endif%}
</div>
{% endblock content %}